# Generated by Django 3.2.8 on 2021-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('student_national_id', models.CharField(max_length=12)),
                ('nationality', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda')], max_length=10)),
                ('registration_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian_contact', models.PositiveIntegerField()),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='images/')),
                ('class_name', models.CharField(blank=True, max_length=10, null=True)),
                ('room_number', models.CharField(blank=True, max_length=13, null=True)),
                ('mentors_name', models.CharField(max_length=10)),
                ('big_sister_name', models.CharField(max_length=10)),
                ('languages', models.CharField(choices=[('E', 'English'), ('K', 'Kiswahili'), ('F', 'French'), ('O', 'Others')], max_length=1)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
